enum FileFormat {
  JPEG
  CR3
}

type Category {
  id: ID!
  name: String!
}

type GPS {
  latitude: Float
  longitude: Float
}

type ExifData {
  make: String
  model: String
  iso: Int
  exposureTime: String
  fNumber: String
  focalLength: String
  dateTimeOriginal: String
  gps: GPS
}

type Metadata {
  id: ID!
  fileName: String!
  categories: [Category!]! # ✅ 단일 `category` 대신 다중 카테고리 `categories`
  imageUrl: String!
  width: Int
  height: Int
  format: String
  size: Int
  exif: ExifData
}

input MetadataSearchCondition {
  categoryName: String
  fileName: String
  fileFormat: FileFormat
}

type Query {
  metadata(searchCondition: MetadataSearchCondition!): [Metadata!]!
  metadataById(id: ID!): Metadata # 특정 id로 데이터 조회
  getCategoryList: [Category!]! # ✅ 카테고리를 `Set`으로 관리 (중복 제거)
}

type Mutation {
  deleteById(id: ID!): Boolean # 특정 id로 데이터 삭제
  # 새로운 메타데이터를 추가하는 Mutation
  addMetadata(
    filePath: String!
    categories: [String!]! # ✅ 여러 개의 카테고리를 받을 수 있도록 수정
  ): Metadata
  addCategory(name: String!): Category # ✅ 새로운 카테고리를 추가하는 Mutation
}
