query GetMetadataById($id: ID!) {
  metadataById(id: $id) {
    id
    fileName
    imageUrl
    categories {
      name
    }
    exif {
      make
      model
    }
  }
}

query GetMetadata($searchCondition: MetadataSearchCondition!) {
  metadata(searchCondition: $searchCondition) {
    id
    fileName
    categories {
      name
    }
    width
    height
    format
    size
    imageUrl
    exif {
      make
      model
    }
  }
}

query GetCategoryList {
  getCategoryList {
    id
    name
  }
}
